### ISSUE TITLE
Extras suddenly not scraped correctly anymore

### ISSUE THREAD

**Issue by karelVD** [tamland/kodi-addon-extras#1]
So I've had the addon 'extras' for a year or so working correctly but suddenly all my extras are added as the movie 'Star In The Night (1945)', meaning I have now over 200 hundred entries of this movie in my library...

I've updated the addon, but it's not fixing the issue. I've reinstalled the addon, but that didn't fix the problem either. And yes, I have named my folders correctly, as well as indicated it correctly in the addon settings.

Anyone having this issue too, or just me?

**Comment by RedSoxFan04** [comment]
I’m having this issue.
