### ISSUE TITLE
UTF-8/non-ASCII characters in file names

### ISSUE THREAD

**Issue by kbpickens** [tamland/kodi-addon-extras#3]
How can UTF-8/non-ASCII characters in file names be handled?  I have at least a few movies with extras that have non-ASCII characters in the file names.  I've put the relevant log lines in the pastebin below.  The Extras directory being loaded at the time contains (non-ASCII filenames are marked with an asterisk [\*] ):
    'Denizens of the Galazy: Humans and Aliens.m4v'
    'Enhancement Pod: Alpha Introduction.m4v'
    'Enhancement Pod: Boulan Bathor Emperor.m4v'
    'Enhancement Pod: Destruction of Mül.m4v'*
    'Enhancement Pod: Emperor Haban-Limaï.m4v'*
    'Enhancement Pod: Empress Aloï.m4v'*
    'Enhancement Pod: Igon Siruss.m4v'
    'Enhancement Pod: Kris Wu 4D Scan.m4v'
    'Enhancement Pod: Kris Wu Set Tour.m4v'
    'Enhancement Pod: K-Trons.m4v'
    'Enhancement Pod: Melo the Converter.m4v'
    'Enhancement Pod: Motion Capture Cameras.m4v'
    'Enhancement Pod: Paradise Alley.m4v'
    'Enhancement Pod: Pearl Guns.m4v'
    'Enhancement Pod: Princess Lĩho-Minaa.m4v'*
    'It Takes Two: Valerian & Laureline'\''s Partnership.m4v'
    'Paper-Ink-Flesh-Blood: Origins.m4v'
    'The Final Element: Visual Effects.m4v'
    'To Alpha and Beyond: Production and Stunts.m4v'

https://paste.kodi.tv/erilutawoy.kodi

**Comment by Samhayne** [comment]
hi kbpickens... I think you're lucky. I also stumbled upon problems there, yesterday.

The log would say something like this for my filenames using this quote character: “
```
Error Type: <type 'exceptions.UnicodeDecodeError'>
Error Contents: 'ascii' codec can't decode byte 0xe2 in position 14: ordinal not in range(128)
```

I fixed it by doing the following:

1) Edit C:\Users\[Username]\AppData\Roaming\Kodi\addons\context.item.extras\plugin.py
2) Go to line 67 and change 
`url = os.path.join(current_path, name)`
to 
`url = os.path.join(current_path, name.decode('utf-8'))`

2) Go to line 75 (or so) and change:
`url = plugin.url_for(youtube, q=args['title'][0] + ' Extras')`
to
`url = plugin.url_for(youtube, q=args['title'][0].encode('utf-8') + ' Extras')`

Works for me now.

I'll attach my plugin.py to this comment.

Hope that helped. :)

[plugin.zip](https://github.com/tamland/kodi-addon-extras/files/3603081/plugin.zip)

**Comment by KarellenX** [comment]
@Samhayne 

Thanks for your fix. Are you able to create a Pull Request so it can be reviewed and merged?

**Comment by pkscout** [comment]
I'm helping with addon maintenace, and this has been resolved with a recent push. The updated addon should be in the Kodi Leia repo in the next day or so.
